trigger: 
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

pr:
  branches:
    include:
      - main

variables:
  - name: EnvironmentDeploy
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: DEV
    ${{ else }}:
      value: devautoapproval

stages:
  - stage: Build

    jobs:
    
      - job: Build
        displayName: Build Job
        steps:
          - script: |
              echo Build Job --> Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)]
            displayName: 'Build Job'
      
      - job: Publish
        dependsOn: Build
        displayName: Publish Job
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        steps:
          - script: |
              echo Publish Job --> Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)]
            displayName: 'Publish Job'

          - template: ./templates/publish-artifact.yml
            parameters:
              ArtifactName: $(ArtifactName)
              ProjectPath: $(ProjectPath)

  - stage: Deploy_DEV
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ./templates/deploy-multistage.yml
        parameters:
          environment: $(EnvironmentDeploy)

  - stage: Deploy_INTG
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ./templates/deploy-multistage.yml
        parameters:
          environment: intg    
