trigger: 
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

pr:
  branches:
    include:
      - main

variables:
  - name: EnvironmentDeploy
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: DEV
    ${{ else }}:
      value: devautoapproval

stages:
  - stage: Build_Stage

    jobs:
    
      - job: Build_Job
        displayName: Build_Job_dn
        steps:
          - script: |
              echo Build Job --> Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)]
              chmod +x ./test.sh
              ./test.sh
            displayName: 'Build_Step_dn'
      
      - job: Publish_Job
        dependsOn: Build_Job
        displayName: Publish_Job_dn
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        steps:
          - script: |
              echo Publish Job --> Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)]
            displayName: 'Publish_Step_dn'

          - template: ./templates/publish-artifact.yml
            parameters:
              ArtifactName: $(ArtifactName)
              ProjectPath: $(ProjectPath)

  - stage: Deploy_DEV_stage
    dependsOn: Build_Stage
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ./templates/deploy-multistage.yml
        parameters:
          environment: $(EnvironmentDeploy)

  - stage: Deploy_INTG_stage
    dependsOn: Build_Stage
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ./templates/deploy-multistage.yml
        parameters:
          environment: intg    
