parameters:
- name: environment
  type: string


#steps:
#    - script: |
#              echo Template Deploy Multistage --> Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)]
#      displayName: 'Template Deploy Multistage '

jobs:
    - deployment: Deploy
      environment: ${{parameters.environment}}
      displayName: Deploy_${{parameters.environment}} $(myvar) Job
      strategy:
          runOnce:
              deploy:
                  steps:
                      - script: |
                            echo Build.Reason [$(Build.Reason)] EnvironmentDeploy [$(EnvironmentDeploy)] parameters.environment ${{parameters.environment}}
                        displayName: 'Deploy - Multistage' 
